name: Update MikroTik Blocklist via BGPView

on:
  schedule:
    - cron: '0 3 * * 1' # Berjalan setiap Senin jam 3 pagi
  workflow_dispatch: # Tombol untuk menjalankan manual

# Memberikan izin pada workflow untuk menulis ke repository
permissions:
  contents: write

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengambil salinan repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Membuat file blocklist dari BGPView
      - name: Generate Blocklist File from BGPView
        run: |
          #!/binbash
          # Daftar ASN (Azure & GCP sudah dihapus)
          ASN_LIST=("16509" "14618" "37963" "45102" "55967" "14061" "31898" "24940")
          FILENAME="Cloud_Blocklist.rsc"

          echo "# Generated on $(date) using BGPView" > $FILENAME
          echo "/ip firewall address-list" > $FILENAME
          echo "remove [find list=Cloud_Blocklist]" >> $FILENAME

          for ASN in "${ASN_LIST[@]}"; do
            echo "--> Memproses ASN: $ASN dari BGPView"
            
            # Menggunakan curl yang menyamar sebagai browser dan jq untuk mem-parsing JSON
            curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" \
            "https://api.bgpview.io/asn/$ASN/prefixes" | \
            jq -r '.data.ipv4_prefixes[].prefix' | \
            sed -e "s/^/add list=Cloud_Blocklist address=/" -e "s/$/ comment=ASN:$ASN/" >> $FILENAME
          done
          echo "# Update Complete" >> $FILENAME

      # Langkah 3: Simpan perubahan (commit & push) kembali ke repository
      - name: Commit and push the updated blocklist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update cloud blocklist via BGPView"
          file_pattern: Cloud_Blocklist.rsc
