name: Gist Read Test

on:
  workflow_dispatch: # Hanya bisa dijalankan manual

jobs:
  read-test:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate and View Gist
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          echo "Memulai tes otentikasi dan pembacaan Gist..."
          echo "${GH_TOKEN}" | gh auth login --with-token
          
          echo "Mencoba melihat Gist dengan ID: ${GIST_ID}"
          gh gist view "$GIST_ID"
