name: Update MikroTik Blocklist

on:
  schedule:
    - cron: '0 2 * * 1' # Berjalan setiap Senin jam 2 pagi
  workflow_dispatch: # Tombol untuk menjalankan manual

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Blocklist File
        run: |
          #!/bin/bash
          ASN_LIST=("16509" "14618" "37963" "45102" "55967" "14061" "31898" "24940") # Daftar ASN (Azure & GCP sudah dihapus)
          FILENAME="Cloud_Blocklist.rsc"

          echo "# Generated on $(date)" > $FILENAME
          echo "/ip firewall address-list" > $FILENAME
          echo "remove [find list=Cloud_Blocklist]" >> $FILENAME

          for ASN in "${ASN_LIST[@]}"; do
            echo "# Fetching ASN: $ASN"
            curl -s "https://stat.ripe.net/data/announced-prefixes/data.txt?resource=AS$ASN" | \
            grep -E '^[0-9]+\.' | \
            sed -e "s/^/add list=Cloud_Blocklist address=/" -e "s/$/ comment=ASN:$ASN/" >> $FILENAME
          done
          echo "# Update Complete" >> $FILENAME

      - name: Update Gist
        uses: exuanbo/actions-sync-gist@v2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: https://gist.github.com/bapelindo/8c1e4d500148bf02966aac48176ba8de
          file_path: 'Cloud_Blocklist.rsc'
