name: Update MikroTik Blocklist via BGPView

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Blocklist File from BGPView
        run: |
          #!/bin/bash
          ASN_LIST=("16509" "14618" "37963" "45102" "55967" "14061" "31898" "24940")
          FILENAME="Cloud_Blocklist.rsc"

          echo "# Generated on $(date) using BGPView" > $FILENAME
          echo "/ip firewall address-list" > $FILENAME
          echo "remove [find list=Cloud_Blocklist]" >> $FILENAME

          for ASN in "${ASN_LIST[@]}"; do
            echo "--> Memproses ASN: $ASN dari BGPView"
            
            # Simpan output mentah dari curl ke file temp.out
            curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" \
            "https://api.bgpview.io/asn/$ASN/prefixes" -o temp.out

            echo "--- Menampilkan isi mentah respons server ---"
            cat temp.out
            echo "-------------------------------------------"
            
            # Coba proses dengan jq, jika gagal akan terlihat dari log di atas
            cat temp.out | jq -r '.data.ipv4_prefixes[].prefix' | \
            sed -e "s/^/add list=Cloud_Blocklist address=/" -e "s/$/ comment=ASN:$ASN/" >> $FILENAME
          done
          echo "# Update Complete" >> $FILENAME

      - name: Commit and push the updated blocklist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update cloud blocklist via BGPView"
          file_pattern: Cloud_Blocklist.rsc
