name: Update MikroTik Blocklist

on:
  schedule:
    - cron: '0 2 * * 1' # Berjalan setiap Senin jam 2 pagi
  workflow_dispatch: # Tombol untuk menjalankan manual

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Blocklist File
        run: |
          #!/bin/bash
          ASN_LIST=("16509" "14618" "37963" "45102" "55967" "14061" "31898" "24940") # Daftar ASN (Azure & GCP sudah dihapus)
          FILENAME="Cloud_Blocklist.rsc"

          echo "# Generated on $(date)" > $FILENAME
          echo "/ip firewall address-list" > $FILENAME
          echo "remove [find list=Cloud_Blocklist]" >> $FILENAME

          for ASN in "${ASN_LIST[@]}"; do
            echo "# Fetching ASN: $ASN"
            # Menggunakan curl untuk mengambil data dan memformatnya menjadi perintah MikroTik
            curl -s "https://stat.ripe.net/data/announced-prefixes/data.txt?resource=AS$ASN" | \
            grep -E '^[0-9]+\.' | \
            sed -e "s/^/add list=Cloud_Blocklist address=/" -e "s/$/ comment=ASN:$ASN/" >> $FILENAME
          done
          echo "# Update Complete" >> $FILENAME

      - name: Update Gist using GitHub CLI
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # Perintah ini memaksa login secara eksplisit menggunakan token Anda
          echo "${GIST_TOKEN}" | gh auth login --with-token
          
          # Setelah login berhasil, perintah edit ini akan berjalan
          gh gist edit "$GIST_ID" Cloud_Blocklist.rsc
