name: Update MikroTik Blocklist

on:
  schedule:
    - cron: '0 2 * * 1' # Berjalan setiap Senin jam 2 pagi
  workflow_dispatch: # Tombol untuk menjalankan manual

# Memberikan izin pada workflow untuk menulis ke repository
permissions:
  contents: write

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengambil salinan repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Membuat file blocklist
      - name: Generate Blocklist File
        run: |
          #!/bin/bash
          ASN_LIST=("16509" "14618" "37963" "45102" "55967" "14061" "31898" "24940")
          FILENAME="Cloud_Blocklist.rsc"
          
          echo "# Generated on $(date)" > $FILENAME
          echo "/ip firewall address-list" > $FILENAME
          echo "remove [find list=Cloud_Blocklist]" >> $FILENAME

          for ASN in "${ASN_LIST[@]}"; do
            echo "--> Memproses ASN: $ASN"
            
            # Menjalankan curl dengan mode verbose dan menyimpan log error ke file terpisah
            curl -v --fail --silent "https://stat.ripe.net/data/announced-prefixes/data.txt?resource=AS$ASN" -o "data.out" 2> "curl_error.log"
            
            echo "--- Log Detail Koneksi (curl_error.log) ---"
            cat curl_error.log || echo "Tidak ada log eror, koneksi mungkin berhasil."
            echo "----------------------------------------"

            # Memproses data jika file output tidak kosong
            if [ -s data.out ]; then
              echo "Data diterima, memproses..."
              cat data.out | grep -E '^[0-9]+\.' | \
              sed -e "s/^/add list=Cloud_Blocklist address=/" -e "s/$/ comment=ASN:$ASN/" >> $FILENAME
            else
              echo "PERINGATAN: Tidak ada data yang diterima atau file output kosong."
            fi
            echo "" # Memberi spasi antar ASN
          done
          echo "# Update Complete" >> $FILENAME

      # Langkah 3: Simpan perubahan (commit & push)
      - name: Commit and push the updated blocklist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update cloud blocklist"
          file_pattern: Cloud_Blocklist.rsc
