- name: Generate Blocklist File
        run: |
          #!/bin/bash
          ASN_LIST=("16509" "14618" "37963" "45102" "55967" "14061" "31898" "24940")
          FILENAME="Cloud_Blocklist.rsc"

          echo "# Generated on $(date)" > $FILENAME
          echo "/ip firewall address-list" > $FILENAME
          echo "remove [find list=Cloud_Blocklist]" >> $FILENAME

          for ASN in "${ASN_LIST[@]}"; do
            echo "--> Memproses ASN: $ASN"
            # Menggunakan curl dengan flag -f (fail silently on server errors) dan menyimpan ke variabel
            DATA=$(curl -sf "https://stat.ripe.net/data/announced-prefixes/data.txt?resource=AS$ASN")
            
            if [ -z "$DATA" ]; then
              echo "PERINGATAN: Tidak ada data yang diterima untuk ASN $ASN. Melewati."
            else
              echo "$DATA" | grep -E '^[0-9]+\.' | \
              sed -e "s/^/add list=Cloud_Blocklist address=/" -e "s/$/ comment=ASN:$ASN/" >> $FILENAME
            fi
          done
          echo "# Update Complete" >> $FILENAME
